FROM node:9

COPY package*.json /usr/src/app/

# Create app directory
WORKDIR /usr/src/app

RUN npm i npm@latest -g && \
    npm i nodemon@latest -g && \
    npm i typescript -g && \
    npm i ts-node mocha -g && \
    npm install

COPY . .

RUN npm run routes; ./node_modules/.bin/tsc -p tsconfig.json --module commonjs --sourceMap --target ES5

CMD [ "npm", "run", "start" ]